resolutions = [[768, 1184]]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
frame_buckets = [77,97]

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250507医美手动'
num_repeats = 5
