#resolutions = [[768, 1184]]
resolutions = [720]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
frame_buckets = [77,97]

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250520视频筛选归总/20250520人工筛选'
num_repeats = 1

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250520视频筛选归总/20250520可灵素材'
num_repeats = 1


[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250520视频筛选归总/20250521交付'
num_repeats = 2