#resolutions = [[768, 1184]]
resolutions = [720]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
frame_buckets = [77,97]

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250508人工标注及可令/20250507人工标注'
num_repeats = 1

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250508人工标注及可令/20250508医美交付归总'
num_repeats = 2
