#resolutions = [[768, 1184]]
resolutions = [720]
enable_ar_bucket = true
min_ar = 0.5
max_ar = 2.0
num_ar_buckets = 7
frame_buckets = [81]

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250526医美训练素材整理fps24/20250520人工筛选'
num_repeats = 1

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250526医美训练素材整理fps24/20250520可灵素材'
num_repeats = 1

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250526医美训练素材整理fps24/20250521交付'
num_repeats = 1

[[directory]]
path = '/home/wangxi/diffusion-pipe/dataset/20250526医美训练素材整理fps24/20250523医美素材整理后'
num_repeats = 1